; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip

board = esp32doit-devkit-v1
; board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 

	bblanchon/ArduinoJson@^7.4.2
	knolleary/PubSubClient@^2.8
	teemuatlut/TMCStepper @ ^0.7.3

monitor_speed = 115200

[platformio]
default_envs = blind

[env:main]
; For OTA upload, use espota
upload_protocol = espota
upload_port=192.168.1.102

; For direct USB upload, use esptool
; upload_protocol = esptool
;upload_port = COM8

[env:adjust_pos]
; For OTA upload, use espota
upload_protocol = espota
upload_port=192.168.1.40

; For direct USB upload, use esptool
; upload_protocol = esptool
;upload_port = COM8

[env:dry_test]
upload_protocol = esptool
build_flags = -D DRY_TEST

[env:blind]

upload_protocol = espota
upload_port=192.168.1.102
build_flags = -D BLIND


[env:dry_test_ota]
upload_protocol = espota
upload_port=192.168.1.40
build_flags = -D DRY_TEST


[env:testing_pressor-sensor]
upload_protocol = esptool
build_flags = -D PRESSURE_SENSOR_TEST
